### PR TITLE
Replace hc launch with hc-spin

### PR DESCRIPTION
**Pull request by c12i**
This PR looks to replace tauri based `hc launch` with electron based [`hc-spin`](https://github.com/holochain/hc-spin) which is already in use with the scaffolding tool's default templates, which provides a better developer experience and cross platform consistency

### CODE REVIEW

**Comment by guillemcordoba** [comment]
I'm not in favor of this... I don't want to migrate to electron, so hc-launch is really critical for me in my workflow to check that my apps work well in tauri. This is why we have custom templates, each template gets to decide which tooling it prefers. If it turns out that the consumers of this template all want to migrate to hc-spin, I'll have to fork it to maintain tauri based tooling. I could do it but it would be a pain I think...

**Comment by matthme** [comment]
What about having one command for each? Even if hc-launch is relevant to check whether things work well in tauri (with the caveat that you still only know that it works on your OS), having the chromium devtools for debugging might still often be useful...

**Comment by guillemcordoba** [comment]
But having one command for each means I'll be downloading `hc-spin` for each project without actually needing it. And since it needs to pack a full electron app I don't suppose it's light... _sigh_ open to suggestions...

**Comment by matthme** [comment]
It does download electron as an npm dependency which is around 250MB yes. I don't have a strong pull, we can also not have it be part of this template. One reason for this PR was I think because the open-dev template is going to be used at ETHDenver in the coming days to showcase [pictogram](https://hackmd.io/UR2kGZO_Q9mKZD6Bt_Z-UQ) and chromium has a better developer experience. But if we think that's important for ETHDenver we can also use a fork of the template for that purpose...

**Comment by c12i** [comment]
> This is why we have custom templates, each template gets to decide which tooling it prefers

I see, I might have made the assumption that this template could use some alignment with the templates in scaffolding with regards to tooling. I am happy to close for now, and as @matthme mentioned we could consider using a fork for the ETHDenver demo

**Pull request closed without merging**
